version: "3"

services:
  nodeosd:
    image: eosio/eos:newest
    command: bash -c "sleep 5; /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888"
    #--delete-all-blocks --mongodb-wipe --genesis-json /opt/eosio/bin/data-dir/genesis.json"
    #command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    #--replay-blockchain --hard-replay-blockchain
    #--delete-all-blocks --genesis-json /opt/eosio/bin/data-dir/genesis.json
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9888:9888
    expose:
      - "8888"
      - "9888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini
      - ./genesis.json:/opt/eosio/bin/data-dir/genesis.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - mongod
    stop_grace_period: 10m

  keosd:
    image: eosio/eos:newest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./wasm:/
      - ./abi:/
    stop_grace_period: 10m

  mongod:
    image: mongo:4.0.1
    #command: mongod --repair
    ports:
      - "27017:27017"
    volumes:
      - mongod-data-volume:/data/db
    stop_grace_period: 10m


volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
  mongod-data-volume:
    external: true

